cabal-version:      3.0
name:               clash-prelude-falsify
version:            0.1.0.0
synopsis:           Falsify support for clash-prelude
-- description:
homepage:           https://clash-lang.org/
license:            BSD-2-Clause
license-file:       LICENSE
author:             QBayLogic B.V.
maintainer:         devops@qbaylogic.com
-- copyright:
build-type:         Simple
extra-doc-files:    CHANGELOG.md
-- extra-source-files:
tested-with:         GHC == 9.6.7, GHC == 9.8.4, GHC == 9.10.3,
                     GHC == 9.12.4

common basic-config
  default-language: Haskell2010

  default-extensions:
    BinaryLiterals
    DataKinds
    NoStarIsType
    RankNTypes
    ScopedTypeVariables
    TypeApplications
    TypeFamilies
    TypeOperators

common warnings
    ghc-options: -Wall

library
    import: warnings, basic-config
    exposed-modules:
        MyLib
        Clash.Falsify.Sized.Vector
    -- other-modules:
    -- other-extensions:
    build-depends:
        base >= 4.18.3.0,
        clash-prelude,
        falsify,
        ghc-typelits-knownnat,
        ghc-typelits-natnormalise,
    hs-source-dirs:   src
    default-language: Haskell2010

test-suite clash-prelude-falsify-test
    import:           warnings
    default-language: Haskell2010
    exposed-modules:
        Clash.Falsify.Sized.Vector
    -- other-modules:
    -- other-extensions:
    type:             exitcode-stdio-1.0
    hs-source-dirs:   test
    main-is:          Main.hs
    build-depends:
        base >=4.18.3.0,
        clash-prelude-falsify,
        falsify,
        tasty,
        tasty-falsify
